addr:
  port: 8081
  host: 127.0.0.1

data:
  dataset: /home/imt/work/dataset/dataset_for_multilabel_classification/

dnn:
  reidentificator: /home/imt/work/gst_reader/deployment/docker/models/intel/person-reidentification-retail-0249/1/FP16-INT8/person-reidentification-retail-0249.xml